# Generated by Django 4.0.6 on 2022-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=100)),
                ('chucvu', models.CharField(max_length=100)),
                ('namsinh', models.CharField(max_length=4)),
            ],
        ),
    ]
